### ISSUE TITLE
Manual installation issue

### ISSUE THREAD

**Issue by Koen-vdl** [ammaraziz/wfi#8]
I encounter an issue with stringr while doing a manual install. Any help with this would be greatly appreciated.

```
Error: package or namespace load failed for ‘stringr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/jurre/miniconda3/envs/wfi_env/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
Execution halted
[Wed Jan  5 14:22:41 2022]
Error in rule SummaryReport:
    jobid: 1
    output: /home/jurre/tmp/test_output/status/process_complete.txt
    shell:

        ./tools/summaryReport.R -i /home/jurre/tmp/test_output/assemblies/ -o /home/jurre/tmp/test_output/assemblies/rename/ -r 'FLU'
        touch /home/jurre/tmp/test_output/status/process_complete.txt

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
oops wfi has run into an issue. Look above, If rule SummaryReport failed there is no need to worry!
Complete log: /home/jurre/bin/wfi_v0.3.2/.snakemake/log/2022-01-05T142232.511230.snakemake.log
```
I installed wfi using the following commands:
```
conda create -n wfi_env -c conda-forge mamba -y
conda activate wfi_env
mamba install -c bioconda snakemake -y
mamba install -c bioconda cutadapt -y
mamba install -c conda-forge r-base -y
mamba install -c r r-ggplot2 r-dplyr r-stringr r-tidyr r-cowplot r-gridExtra -y

mamba install biopython -y 
mamba install -c r r-optparse
```

I also installed biopython which seems to be missing after running `snakemake -np`
`mamba install biopython -y`

I then also installed optparse as it seems to be missing as wel:
`mamba install -c r r-optparse -y`

**Comment by ammaraziz** [comment]
Thanks for trying out the pipeline and submitting an issue. Yes biopython is missing from the instructions, thanks for the heads up. 

What OS are you using? I'm guessing linux. Try to install `stringi` to see if that helps.

**Comment by Koen-vdl** [comment]
Thanks for getting back so soon to my message @ammaraziz .
I'm running Ubuntu 20.04.3 LTS

Tried installing stringi but it was already installed (dependency of other R-package).
`mamba install -c r r-stringi  -y`

Still getting the same error message I'm afraid.

**Comment by ammaraziz** [comment]
The error seems to be associated with `stringi` can you try loading `stringi` in R to see if it works? Activate the environment first, enter R and run `library("stringi")`.

If this doesn't work, remove `stringi` and reinstall. 

Also what R version was installed?

**Comment by ammaraziz** [comment]
See this issue for more info on this error 
https://github.com/tidyverse/stringr/issues/320

**Comment by Koen-vdl** [comment]
I'm running R version 4.1.2 
`stringi `indeed fails to compile properly with:
`mamba install -c r r-stringi `
I manually installed it in R but I run into a new issue. 

```
input: /home/jurre/tmp/test_output/assemblies/
output: /home/jurre/tmp/test_output/assemblies/rename/
Error: Can't select last column when input is empty
Backtrace:
     █
  1. ├─global::main()
  2. │ └─global::file_finder(base_location)
  3. │   └─`%>%`(...)
  4. ├─dplyr::pull(.)
  5. ├─dplyr::select(., last_col())
  6. ├─dplyr:::select.data.frame(., last_col())
  7. │ └─tidyselect::eval_select(expr(c(...)), .data)
  8. │   └─tidyselect:::eval_select_impl(...)
  9. │     ├─tidyselect:::with_subscript_errors(...)
 10. │     │ ├─base::tryCatch(...)
 11. │     │ │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
 12. │     │ │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 13. │     │ │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
 14. │     │ └─tidyselect:::instrument_base_errors(expr)
 15. │     │   └─base::withCallingHandlers(...)
 16. │     └─tidyselect:::vars_select_eval(...)
 17. │       └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 18. │         └─tidyselect:::eval_c(expr, data_mask, context_mask)
 19. │           └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 20. │             └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 21. │               └─tidyselect:::eval_context(expr, context_mask)
 22. │                 └─rlang::eval_tidy(expr, context_mask)
 23. └─tidyselect::last_col()
Execution halted
[Wed Jan  5 20:44:42 2022]
Error in rule SummaryReport:
    jobid: 1
    output: /home/jurre/tmp/test_output/status/process_complete.txt
    shell:

        ./tools/summaryReport.R -i /home/jurre/tmp/test_output/assemblies/ -o /home/jurre/tmp/test_output/assemblies/rename/ -r 'FLU'
        touch /home/jurre/tmp/test_output/status/process_complete.txt

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
oops wfi has run into an issue. Look above, If rule SummaryReport failed there is no need to worry!
Complete log: /home/jurre/bin/wfi_v0.3.2/.snakemake/log/2022-01-05T204440.501671.snakemake.log
```

**Comment by ammaraziz** [comment]
Glad to hear stringi issue was fixed. 

For the new error can you post the results of `ls` in the assemblies directory. Also can you confirm the IRMA runs were successful in generating data?

**Comment by Koen-vdl** [comment]
No output is being produced. If I manually make an output folder it gets deleted after the script crashes out.
Not sure how to proceed. 
FYI the input folder contains a compressed set of ONT reads (filename BC26.fastq.gz).

**Comment by ammaraziz** [comment]
I think snakemake is deleting the output folders. It's designed that way.

The file name structure does not match the pattern for ont. You need to modify the pattern in `wfi_config.yaml file`. For you the pattern should be :

    pattern_ont : /{sample_name}.fastq.gz

That should hopefully allow you to run the pipeline with your samples. Alternatively, you can rename your samples from `BC26.fastq.gz` to `BC26_S1.fastq.gz` and the pipeline with default ont pattern will work. They can all have `_S1`.

Finally, if you have previous IRMA output, you can run the summary script directly:

    summaryReport.R -i /home/jurre/tmp/test_output/assemblies/ -o /home/jurre/tmp/test_output/assemblies/rename/ -r 'FLU'

Let me know how you go.

**Comment by Koen-vdl** [comment]
Thanks for all the support @ammaraziz 

The script still failed when changing the filename to BC26_S1.fastq.gz with the default ont pattern:
pattern_ont : /{sample_name}_{sample_number}.fastq.gz`
Error:
````
MissingInputException in line 231 of /home/jurre/bin/wfi_v0.3.2/snakefile:
Missing input files for rule filter_single:
/home/jurre/tmp2/BC26.fastq.gz
```
As you suggested renamed the reads to their original name BC26.fastq.gz and I changed the ont pattern to:
`pattern_ont : /{sample_name}.fastq.gz`
Now the pipeline finally starts and output is being produced, although I get stuck with a new IRMA error. 

```
Error in rule irma_single:
    jobid: 2
    output: /home/jurre/tmp2/output/assemblies/BC26/contigs.fasta, /home/jurre/tmp2/output/status/irma_BC26.txt
    log: /home/jurre/tmp2/output/logs/irma_BC26.txt (check log file(s) for error message)
    shell:

            # run IRMA
            IRMA FLU-minion /home/jurre/tmp2/output/qualtrim/BC26.fastq BC26 1>> /home/jurre/tmp2/output/logs/irma_BC26.txt
            # move output to folder
            mv $PWD/BC26 /home/jurre/tmp2/output/assemblies/

            myarray=(`find ./ -maxdepth 1 -name "*.fasta"`)
            if [[ ${myarray[@]} -gt 0 ]]
                echo ${myarray[@]}
            then
                python tools/geneMover.py /home/jurre/tmp2/output/assemblies/BC26/ /home/jurre/tmp2/output/assemblies/BC26/contigs.fasta {HA,NA,MP,NS,NP,PA,PB1,PB2} 2>> /home/jurre/tmp2/output/logs/irma_BC26.txt
                cat /home/jurre/tmp2/output/assemblies/BC26/amended_consensus/*.fa 1> /home/jurre/tmp2/output/assemblies/BC26/amended_consensus/amended.contigs.fasta 2>>/home/jurre/tmp2/output/logs/irma_BC26.txt
                mkdir -p /home/jurre/tmp2/output/vcf/BC26/ && cp /home/jurre/tmp2/output/assemblies/BC26/*.vcf /home/jurre/tmp2/output/vcf/BC26/
                echo irma produced stuff this is temp ignore > /home/jurre/tmp2/output/status/irma_BC26.txt
            else
                echo temp file ignore > /home/jurre/tmp2/output/assemblies/BC26/contigs.fasta
                touch temp file ignore > /home/jurre/tmp2/output/status/irma_BC26.txt
            fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
oops wfi has run into an issue. Look above, If rule SummaryReport failed there is no need to worry!
Complete log: /home/jurre/bin/wfi_v0.3.2/.snakemake/log/2022-01-10T150526.694377.snakemake.log
```

I might be missing something obvious. I don't work in virology; I'm just trying to help a mate out by setting up your pipeline on our server.

**Comment by ammaraziz** [comment]
The pipeline is unfortunately very finicky and was designed specifically for in-house use. 

Can you run the snakemake pipeline with `-k` (keep going). IRMA run can complete with no fasta files output which causes an error.

**Comment by ammaraziz** [comment]
If you require help please reopen this issue.
